### ISSUE TITLE
自动化发全平台包

### ISSUE THREAD

**Issue by ngot** [fibjs/fibjs#185]
## 目的

   通过打tag方式，发布全平台包

## 平台

linux_i386, linux_amd64, linux_arm, linux_arm64, 
linux_mips, linux_mips64,
osx, win, win32, brew(fullsrc)

## 包名字规范

fibjs-{version}-{os}-{platform}

fulllist:

- `fibjs-v1.0.0-linux-x64`
- `fibjs-v1.0.0-linux-x86`
- `fibjs-v1.0.0-linux-arm`
- `fibjs-v1.0.0-linux-arm64`
- `fibjs-v1.0.0-linux-mips`
- `fibjs-v1.0.0-linux-mips64`
- `fibjs-v1.0.0-darwin-x64`
- `fibjs-v1.0.0-win-x64`
- `fibjs-v1.0.0-win-x86`
- `fullsrc.zip`

## 发布流程

所有发布分支代码合并到master，并且通过了所有测试。确定版本号后，通过打tag方式，来触发自动发布。

每次发布，需要在Release页面写上当前的 Release Notes（也可以自动化做掉）。

## 版本发布节奏

待补充

**Comment by onceyoung** [comment]
666

**Comment by ngot** [comment]
finally, we decide:

- fibjs-darwin-x64
- fibjs-linux-arm
- fibjs-linux-arm64
- fibjs-linux-mips
- fibjs-linux-mips64
- fibjs-linux-x64
- fibjs-linux-x86
- fibjs_gui_windows_x64.exe
- fibjs_gui_windows_x86.exe
- fibjs_windows_x64.exe
- fibjs_windows_x86.exe
- installer-darwin-x64.sh
- installer-linux-arm.sh
- installer-linux-arm64.sh
- installer-linux-mips.sh
- installer-linux-mips64.sh
- installer-linux-x64.sh
- installer-linux-x86.sh
- installer_windows_x64.exe
- installer_windows_x86.exe

**Comment by ngot** [comment]
https://github.com/fibjs/fibjs/pull/206
