### ISSUE TITLE
关于取消 require 顶层目录的提案

### ISSUE THREAD

**Issue by xicilion** [fibjs/fibjs#223]
在 fibjs 中，代码启动目录缺省作为 require 的顶层目录，比如：

a.js
``` JavaScript
var b = require('b');
```

b.js
``` JavaScript
exports.v = 100;
```

在 fibjs 中是可以工作的，而在 node.js 里是不支持的。在 node.js 里，a.js 必须以相对路径才可以成功：
``` JavaScript
var b = require('./b');
```

支持顶层目录，会带来一些便利，但是也会引入一些隐患。比如在当前目录调试好的代码，如果执行目录不是当前目录，就会执行错误。这样就很不利于代码的独立部署。

以上的代码，在代码目录，`fibjs t.js` 是可以成功的，但是不在代码目录，`fibjs folder/a.js` 就会出错。而按照 node.js 的约束来书写，则不会引入这样的问题。

因此，我考虑在下一版中，取消这个特性，采用 node.js 一样的搜寻列表。

**Comment by ngot** [comment]
赞成。

真实的生产环境启动目录往往和开发环境不同。

比如：

开发环境下，用定制的 dev-tools 来启动应用，这个时候启动路径是不确定的，不同的项目可能不同。

生产环境下，会用一个入口文件来启动如 `fibjs app.js`， 这个入口文件，路径其实也不确定。可能不同公司环境不同，规范不同都不同。

所以，开发环境下和生产环境下，启动路径无关一致性，还是非常重要的。

赞同这个改动。

最后，这个 `Break Change` 放到 0.4.x 中发布

**Comment by xicilion** [comment]
已经实现，暂未启用。
可使用 --noroot 参数禁止启动目录模块。
