### ISSUE TITLE
version "t1"?

### ISSUE THREAD

**Issue by ilovezfs** [fibjs/fibjs#251]
I'm not quite sure how to interpret a version named "t1"

In Homebrew should we distribute this as "fibjs 1"? What would be the next version to expect? t1.0.1?

**Comment by ngot** [comment]
@ilovezfs just for test. I have deleted it. Sorry for the misunderstanding.

**Comment by ilovezfs** [comment]
@ngot no problem at all. Glad I asked! In the future you can check the box on GitHub for "pre-release" (to attempt) to avoid confusion.

**Comment by ngot** [comment]
@ilovezfs I am testing the release script recently. I will check the "pre-release" box and name the test tag prefix "test-x.y.x".

**Comment by ilovezfs** [comment]
Perfect :)
