### ISSUE TITLE
关于console.add：希望在文件名中指定“日期时间”的占位位置

### ISSUE THREAD

**Issue by gmxyb** [fibjs/fibjs#254]
比如：
console.add({
   type: "file",
   path: "path/to/file_%s.log",  // 用 %s 或其他的符号指定日期时间的位置
   split: "30m",  // 选项，可选值为 "day", "hour", "minute", "###k", "###m", "###g"
   count: 10 // 选项，可选范围为 2-128，指定此项时必须提供 split
});

**Comment by xicilion** [comment]
用 %s 想法比较好，如果名称中没有 %s，则按照之前的逻辑，添加到尾部。
