### ISSUE TITLE
function path.join difference result with nodejs when parameter is "/"

### ISSUE THREAD

**Issue by vickyjam** [fibjs/fibjs#273]
filename: 001_path.join.js
test code:
```
var path = require('path');
console.log(path.join(__dirname, '/') == path.join(__dirname, './'));
```

run result:
> $ node -v
> v8.0.0
> $ node 001_path.join.js
> true
> $ fibjs -v
> v0.5.0/v0.3.0-236-g301164a3e
> $ fibjs 001_path.join.js
> false

**Comment by xicilion** [comment]
fixed.
