### ISSUE TITLE
入门文档友好度问题

### ISSUE THREAD

**Issue by xin-6** [fibjs/fibjs#352]
我用一个刚装完CentOS7.2的系统，按照开发指南一步一步往下走，到编译这一步一直出错，重复三四次都不行，git clone 下来的test文件夹下执行 fibjs main.js 一样报错，这样的情况怎么能让人有继续深入的想法呢？吐槽完了说正事儿：
git  clone官方代码下来后执行： sh build release 编译结果报错是这样，谷歌错误后各种函数库都安装配置后依然报错，求解
[100%] Built target editline
Linking CXX executable /root/fibjs/fibjs/bin/Linux_amd64_release/gtest_test
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[2]: *** [/root/fibjs/fibjs/bin/Linux_amd64_release/gtest_test] Error 1
make[1]: *** [CMakeFiles/gtest_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by ngot** [comment]
直接这里下载 http://fibjs.org/download/ 预编译版本使用，无需自己编译。

如果希望自己研究源码，尝试自己编译的话，参考这里 https://github.com/fibjs/fibjs/blob/master/BUILDING.md
