### ISSUE TITLE
fibjs中如何编写插件？

### ISSUE THREAD

**Issue by xwb1966** [fibjs/fibjs#386]
如何编写插件，让fibjs能够访问我的设备，如读卡器、指纹仪什么的？最好能够让fibjs调用DLL/so。

**Comment by ngot** [comment]
目前 fibjs 的扩展方式支持：
- JavaScript 代码扩展，可以发不成 npm 包
- WebAssembly 扩展，可以使用任何能够编译到 WASM 的语言，来编写 fibjs 的扩展

不过，遗憾的是，目前尚不支持直接运用 C/C++ 来扩展 fibjs ，也尚不支持 调用 DLL/SO .

这里可以来跟进讨论这个需求的。

**Comment by gmxyb** [comment]
希望 早日支持 dll 方式扩展！~

**Comment by illuspas** [comment]
@gmxyb 用emscripten呀，nodejs那套c++扩展还要考虑跨平台问题

**Comment by gmxyb** [comment]
@illuspas 呃。。不是很了解emscripten，貌似 c++ to asm.js ？为了提高性能的纯算法比较合适用这个吧？，其他的，比如操作硬件什么的，赶脚还是没有 dll 方便。。

**Comment by asionius** [comment]
@gmxyb 我们也有和你类似的需求，目前是通过自定义 fibjs 模块并动态加载 DLL/SO 来实现。可以参考这里[https://github.com/asionius/fibjs-ceph](https://github.com/asionius/fibjs-ceph)的实现
另外，我们也在期待 fibjs 能够早日推出标准的 c/c++ 扩展接口
