### ISSUE TITLE
是否有必要将Buffer.copy的实现从memcpy 改成 memmove

### ISSUE THREAD

**Issue by zywww** [fibjs/fibjs#388]
https://github.com/fibjs/fibjs/blob/33f3c01fc44dc678c93ac520196409cfa7808d5d/fibjs/src/global/Buffer.cpp#L575
此处的memcpy是否有必要改成memmove？
memcpy相对memmove增加了内存重叠的判断,更加安全？

`this.m_Buffer.copy(this.m_Buffer,0,this.m_Offest,this.m_Tail);`
因为在使用Buffer时候，可能会在自己身上调用copy，如上用法

**Comment by ngot** [comment]
这个issue没看懂是要表达什么意思。

**Comment by ngot** [comment]
先关了。等补充信息完成，能看懂了，再打开。

**Comment by zywww** [comment]
@ngot

**Comment by ngot** [comment]
@zywww 根据man手册：

The memcpy() function copies n bytes from memory area src to memory area dst.  If dst and src overlap, behavior is undefined.  Applications in which dst and src might overlap should use memmove(3) instead.

貌似不能这么改。

**Comment by ngot** [comment]
http://en.cppreference.com/w/c/string/byte/memmove 根据cpp的文档，也可以知道，在没有 overlap 的时候，会自动fall back 到 memcpy ，memcpy 无法确保安全。

**Comment by zywww** [comment]
这代码里用的就是 memcpy 啊，所以说用 memmove 替换了

**Comment by ngot** [comment]
@zywww 还真是。要不来个 PR ?

**Comment by xicilion** [comment]
@zywww 这里可以修改使用 memmove，提个 PR 吧。

**Comment by zywww** [comment]
好了 @xicilion

**Comment by xicilion** [comment]
@zywww 你需要切换到 dev 分支上提交 pr.

**Comment by zywww** [comment]
@xicilion 好了
