### ISSUE TITLE
http.Client()导致socket资源耗尽

### ISSUE THREAD

**Issue by little-pan** [fibjs/fibjs#393]
-- fibjs版本 2017-12-28, Version v0.21.0
-- 操作系统 windows 8.1 x64

场景描述：
 case-1.  main coroutine每趟创建100子coroutine请求http服务（共100个请求），并等待子coroutine都处理完成，然后进行下一趟请求。100个子coroutine处理完后关闭socket（或不关闭socket，效果一样），并通知main coroutine处理完成。如此循环反复，27~30秒后大量子coroutine报请求失败（网络设置出错或地址错误）。
 case-2.  main coroutine每趟创建100子coroutine请求http服务（共100个请求），并等待子coroutine都处理完成，然后等待250毫秒，再进行下一趟请求。100个子coroutine处理完后关闭socket（或不关闭socket，效果一样），并通知main coroutine处理完成。如此循环反复，大约5小时后子coroutine偶尔报请求失败（网络设置出错或地址错误），fibjs http server报空指针错误。

问题分析：
  case-1. keep-alive的socket连接没法重用？!
  case-2. socket资源不足，导致地址错误，或空指针错误？貌似错误信息不准确。

**Comment by xicilion** [comment]
能给出再现代码吗？

**Comment by little-pan** [comment]
// http client
// 
const http = require('http');
const co   = require("coroutine");
const net  = require("net");

const ts = new Date().getTime();
const client = new http.Client();
const n = 100;
let sem = new co.Semaphore(n);
let c = 0, reqs = 0, sucs = 0, errs = 0;

for(let k = 0, ec = 0;; ++k){
	for(let i = 0; i < n; ++i){
		sem.acquire();
		co.start(function(){
			let res = null;
			try{
				reqs++;
				errs++;
				// - request method a
				res = client.request('GET', 'http://localhost:8000', {
					"headers": {
						"Connection": "keep-alive",
				//		"Connection": "close"
					}
				});
				// - request method b
				// issue: TypeError: http.HttpRequest is not a constructor??
				//req = new http.HttpRequest();
				//req.method = "GET";
				//req.address= "http://localhost:8000";
				//req.keepAlive = true;
				//res = client.request(new net.Socket(), req);
				//console.log("statusCode = " + res.statusCode);
				const sc = res.statusCode;
				if(sc !== 200){
					console.log("statusCode = " + sc+", statusMessage = " + res.statusMessage);
					throw {message: res.statusMessage};
				}
				res.readAll();
				res.stream.close();
				c++;
				errs--;
			}finally{
				sem.release();
				if(res != null){
					//res.socket.close();
				}
			}
		});
	}
	for(let i = 0; i < n; ++i){
		sem.acquire();
	}
	for(let i = 0; i < n; ++i){
		sem.release();
	}
	if(c !== n){
		if(++ec > 3){
			console.log("error occurs: exit, pass = " + k);
			break;
		}
	}
	sucs += c;
	c = 0;
	//co.sleep(200);
}
let te = new Date().getTime();
console.log("requests %d: sucs = %d, errs = %d, time = %dms", reqs, sucs, errs, (te-ts));

//  --------------------------------------------------------------------------------------------------------------
// http server
// 
// 20k~ qps
const http = require('http');
const io   = require('io');
const db   = require('db');

const encoding = 'utf-8';
const dburl = "mysql://root:123456@localhost/test";
const cpool = [];

var server = new http.Server(8000, (req)=>{
	var res = req.response;
	var i, n = 1000, sum = 0;
	var conn, accs, acc = {}, accCnt = 0;

	// Connection: null??
	//const chd = "Connection";
	//console.log("%s: %s", chd, req.headers.first(chd));
	//console.log("Connection: keep-alive? %s", req.keepAlive);
	// calc
	//for(i = 1; i <= n; ++i){
	//	sum += i;
	//}
	const id = parseInt((new Date().getTime()%10000000)*Math.random());
	conn = getCnxn();
	accs = conn.execute("select id, balance, name from accounts where id=?", id);
	if(accs.length > 0){
		acc.id = accs[0].id;
		acc.balance = accs[0].balance;
		acc.name = accs[0].name;
	}
	//accs = conn.execute("select count(*) cnt from accounts where id < ?", 1000000);
	//accCnt = accs[0].cnt;
	releaseCnxn(conn);

	res.setHeader("Content-Type", "text/html;charset="+encoding);
	res.setHeader("Date", new Date());
	var buf = new Buffer(new Date()+' hello world, sum =' + sum + 
		", acc = " + (acc.name||"") + ", acc-cnt = "+accCnt, encoding);
	res.write(buf);
});

server.run();

function getCnxn(){
	var c = cpool.pop();
	if(c){
		return c;
	}
	return db.open(dburl);
}

function releaseCnxn(c){
	return cpool.push(c);
}

**Comment by little-pan** [comment]
HttpHandler: C:\Users\pzp\js\fibjs\fhttpd.js:51:12
        return db.open(dburl);
                  ^
Error: [1214] 指定的网络名格式无效。
    at getCnxn (C:\Users\pzp\js\fibjs\fhttpd.js:51:12)
    at http.Server (C:\Users\pzp\js\fibjs\fhttpd.js:24:9)

**Comment by little-pan** [comment]
C:\Users\pzp\js\fibjs\fhttpc.js:20:18
                                res = client.request('GET', 'http://localhost:8000', {
                                             ^
Error: [52] 由于网络上有重名，没有连接。如果加入域，请转到“控制面板”中的“系统”更改计算机名，然后重试。如果加入工作组，请选择其他工作组名。
    at Fiber.<anonymous> (C:\Users\pzp\js\fibjs\fhttpc.js:20:18)
C:\Users\pzp\js\fibjs\fhttpc.js:20:18
                                res = client.request('GET', 'http://localhost:8000', {
                                             ^
Error: [52] 由于网络上有重名，没有连接。如果加入域，请转到“控制面板”中的“系统”更改计算机名，然后重试。如果加入工作组，请选择其他工作组名。
// ......

**Comment by little-pan** [comment]
>netstat -ano
活动连接

  协议     本地地址              外部地址               状态            PID
  TCP    0.0.0.0:8000           0.0.0.0:0              LISTENING       8780
  TCP    127.0.0.1:49158        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49159        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49161        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49162        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49163        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49164        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49165        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49166        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49167        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49168        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49172        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49173        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49174        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49175        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49176        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49178        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49180        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49182        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49184        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49186        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49188        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49190        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49192        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49194        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49196        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49198        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49200        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49202        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49204        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49206        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49208        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49210        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49212        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49213        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49214        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49215        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49216        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49217        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49218        127.0.0.1:8000         TIME_WAIT       0
  TCP    127.0.0.1:49219        127.0.0.1:8000         TIME_WAIT       0
// 省略10000行...

**Comment by xicilion** [comment]
目前 http client 不支持 keep-alive。
我在 mac 上运行这段代码，把数据库部分注释掉，是好的。
localhost 找不到，你看看命令行 ping localhost 是不是通，如果不通，改成 127.0.0.1 试试看。
return db.open(dburl); 不能打开数据库，应该是同一个问题，localhost 命名没找到。
