### ISSUE TITLE
提供给沙盒的模块不能是一个Map

### ISSUE THREAD

**Issue by PowerGit** [fibjs/fibjs#394]
new Sandbox({a: new Map()}).require(xxx)报错

`#
# Fatal error in src\heap\heap.cc, line 3418
# Check failed: map->instance_type() == JS_REGEXP_TYPE || map->instance_type() == JS_OBJECT_TYPE || map->instance_type() == JS_ERROR_TYPE || map->instance_type() == JS_ARRAY_TYPE || map->instance_type() == JS_API_OBJECT_TYPE || map->instance_type() == WASM_INSTANCE_TYPE || map->instance_type() == WASM_MEMORY_TYPE || map->instance_type() == WASM_MODULE_TYPE || map->instance_type() == WASM_TABLE_TYPE || map->instance_type() == JS_SPECIAL_API_OBJECT_TYPE.
#

==== C stack trace ===============================

        (No symbol) [0x00007FF6766EB9B1]
        (No symbol) [0x00007FF67653597A]
        (No symbol) [0x00007FF67659CBC4]
        (No symbol) [0x00007FF6765C0589]
        (No symbol) [0x00007FF6765FC9D8]
        (No symbol) [0x00007FF676521016]
        (No symbol) [0x00007FF676282C28]
        (No symbol)`

**Comment by xicilion** [comment]
已修复。
