### ISSUE TITLE
mysql执行insert命令好像不能返回insertid

### ISSUE THREAD

**Issue by kevinchen8621** [fibjs/fibjs#397]
执行以下代码，得到的result为空数组 []，如果请求是 UPDATE 或者 INSERT，返回结果还会包含 affected 和 insertId，mssql 不支持 insertId，好像没有实现返回insertId。

users表有自增长字段id

let sql = "INSERT INTO `users` (`firstName`,`lastName`) VALUES ('John','Hancock');"
let result = this.connection.execute(sql)
console.log(result)

**Comment by xicilion** [comment]
console.log(result) 只会输出数组的内容，数组对象上的属性会被忽略，所以你看不到 insertId。实际是有返回的，我刚测了一下，是有的。

**Comment by xicilion** [comment]
已更新测试用例，包含了 insertId 的测试。

**Comment by kevinchen8621** [comment]
好的，谢谢
