### ISSUE TITLE
新手想尝试一下，怎么入门

### ISSUE THREAD

**Issue by 270034480** [fibjs/fibjs#398]
听说fibjs并发性能很强，想在win10电脑上安装一下fibjs，试试看是否适合我们项目。但是没有找到这方面的资料，怎么在电脑上把开发环境搭建起来，跑几个例子试试看，熟悉熟悉开发模式，并按部就班的学习。
有大神指点一下吗？

**Comment by xicilion** [comment]
http://fibjs.org

**Comment by gmajrtfp** [comment]
win10 应该和win7一样吧，和nodejs一样，只是把启动的node.exe app.js换成fibjs.exe app.js
