### ISSUE TITLE
请问下有没有热重启？

### ISSUE THREAD

**Issue by gmajrtfp** [fibjs/fibjs#400]
原来node用的pm2，有个平滑重启，fibjs有没有类似的功能？

**Comment by xicilion** [comment]
pm2 是进程重启，不是平滑重启，fibjs 可以使用 sandbox 实现热重启。
http://fibjs.org/docs/guide/server-hot-update.md.html

**Comment by ngot** [comment]
pm2 的平滑重启是假的平滑，它只是很单纯的切流重启，有个等待时间间隔，如果某个请求超过了这个时间间隔，这个请求就失败了。

fibjs 内的 sandbox 能够智能的检测是不是真的处理请求，会平滑的替换掉就的代码对象为新的，之前的请求依然可以继续处理，而不会丢失。
