### ISSUE TITLE
API文档好多参数都不知道从哪里来的

### ISSUE THREAD

**Issue by gmajrtfp** [fibjs/fibjs#401]
能不能在文档里多点例子
比如说httpserver的路由，原来有个路由“*”可以处理所有请求，再用req.next()执行具体的请求，但fibjs的req好像没有next函数

**Comment by xicilion** [comment]
http://fibjs.org/docs/guide/hello.md.html
http://fibjs.org/docs/manual/object/ifs/routing.md.html
