### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by lhkzh** [fibjs/fibjs#405]
1.提供js调用模版，给开发工具 提示代码用。
2.搞个官方QQ群

现在写代码，ide没联想提示--. 遇到坑没交流群

**Comment by milkman2014** [comment]
刚想问有无官方维护的**TypeScript**类型声明文件 😄 [TypeSearch](https://aka.ms/types)上没有，看来得自行解决了:)

**Comment by richardo2016** [comment]
@lhkzh 你好，请发您的微信到 richardo2016@gmail.com 我来拉你进群
