### ISSUE TITLE
是否支持本地socket

### ISSUE THREAD

**Issue by Gaubee** [fibjs/fibjs#406]
net模块并没有nodejs的`net.createServer`，所以不知道怎么创建一个address family为AF_UNIX的UNIX Domain Socket。

**Comment by asionius** [comment]
支持 socket, 戳这里
[http://fibjs.org/docs/manual/object/ifs/socket.md.html](http://fibjs.org/docs/manual/object/ifs/socket.md.html)

**Comment by Gaubee** [comment]
我的意思是ipc-pipe的支持。

**Comment by asionius** [comment]
不知道你要的是不是这个
[http://fibjs.org/docs/manual/module/ifs/io.md.html#bridge](http://fibjs.org/docs/manual/module/ifs/io.md.html#bridge)
socket 支持数据单向 pipe 和双向 pipe

**Comment by asionius** [comment]
暂时不支持

**Comment by richardo2016** [comment]
> 暂时不支持

现在 vender 填入了 UV，是不是可以考虑基于 UV 在做跨平台的 ipc-pipe 支持了

**Comment by xicilion** [comment]
0.33 dev 已经支持了。
