### ISSUE TITLE
Buffer对象的readUIntLE ，readUIntBE，writeIntLE，writeIntBE的问题

### ISSUE THREAD

**Issue by illuspas** [fibjs/fibjs#408]
这4个函数在Nodejs里是可以设置读取多少字节的
```
buf.readUIntLE(offset, byteLength[, noAssert])
```

fibjs里怎么说的是支持最大48位，但没有参数传入来设置？ 源码里也是写死的
```
result_t Buffer::readUIntLE(int32_t offset, bool noAssert, int64_t& retVal)
{
    READ_U_NUMBER_48(uint64_t, true);
}
```

**Comment by xicilion** [comment]
这里的实现是有些不兼容，回头我来看一下

**Comment by illuspas** [comment]
@xicilion 另外我发现一个问题
当readIntLE 48位的结果是错误的，对比
https://nodejs.org/api/buffer.html#buffer_buf_readintle_offset_bytelength

fibjs输出
-2b9078563412
1234567890ab

**Comment by xicilion** [comment]
fixed. fc20c74cfb9ede5a4b02a810dec3b5bfce26409f
