### ISSUE TITLE
Can I know what's the difference from node-fibers project?

### ISSUE THREAD

**Issue by dsonet** [fibjs/fibjs#411]
Also found this project:
https://github.com/laverdet/node-fibers

Can someone let me the key difference between them?

Thank you very much.

**Comment by asionius** [comment]
Fibjs is a javascript runtime built on Chrome's V8 JavaScript engine. It acts like what some static and dynamic language such as `go`, `python` and so on do.
You can create a web application, a system progress, a graphical user interface application and many other projects which you could imagine using Fibjs as solution. It has no relationship with the project you mentioned above.
If you will, you can refer to the [official website of Fibjs](http://fibjs.org) for more details. Welcome to the ecosystem :-)!
