### ISSUE TITLE
Crash: "Parameter not optional" in vm.SandBox.require()

### ISSUE THREAD

**Issue by little-pan** [fibjs/fibjs#412]
**// 1. Crash的情况**
// app.js
var http = require("http");
var vm = require("vm");
var coroutine = require("coroutine");

function new_web() {
    return new vm.SandBox({
        mq: require("mq")
    }).require("./web.js"); **// Parameter not optional!!**
}

// 每 1s 重新载入一遍 ./web.js 文件以更新 srv 的 handler
coroutine.start(function() {
    for (;;) {
        coroutine.sleep(1000);
        svr.handler = new_web();
    }
})

var svr = new http.Server(8080, new_web());

svr.run();

**// 2. OK的情况**
// app.js
var http = require("http");
var vm = require("vm");
var coroutine = require("coroutine");

function new_web() {
    return new vm.SandBox({
        mq: require("mq")
    }).require("./web.js", "./"); **// OK** 
}

// 每 1s 重新载入一遍 ./web.js 文件以更新 srv 的 handler
coroutine.start(function() {
    for (;;) {
        coroutine.sleep(1000);
        svr.handler = new_web();
    }
})

var svr = new http.Server(8080, new_web());

svr.run();

**问题：vm.SandBox.require(path, base)里的base属性必须指定！但官网例子里是可以不指定的。**
环境：fibjs-v0.23.0-windows-x64.

**Comment by xicilion** [comment]
不指定是错误的，我来改一下官网例子。
