### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by MindFy** [fibjs/fibjs#462]
1. git拉取源碼編譯成功後，運行fibjs 報“段错误 (核心已转储)”。
2. 官方網站執行curl -s http://fibjs.org/download/installer.sh|sh一鍵安裝，運行fibjs --cov test.js 報“段错误 (核心已转储)”。
系統ubuntu18.04

**Comment by xicilion** [comment]
ubuntu 18 的 gcc 编译 v8 会出现这个错误，建议使用 ubuntu 16 编译。

**Comment by MindFy** [comment]
ok 谢了。
