### ISSUE TITLE
http head method error

### ISSUE THREAD

**Issue by lhkzh** [fibjs/fibjs#521]
require("http").request("HEAD","http://fibjs.org/css/common.css")

repl:1:17
require("http").request("HEAD","http://fibjs.org/css/common.css")
                ^
Error: HttpMessage: body is not complate.
    at repl:1:17

**Comment by richardo2016** [comment]
fixed by this [commit](https://github.com/fibjs/fibjs/commit/e03f90636cfe83ae29d7a50217b2ee4fcc3fd55f)
