### ISSUE TITLE
How can I use an http/https proxy with fibjs' http.request?

### ISSUE THREAD

**Issue by jim4node** [fibjs/fibjs#528]
I wanna make an outgoing HTTP/HTTPS call from fibjs, using the standard http.request(or .get) method. But I cannot reach the remote site directly from my network, so I need to go through a proxy.
I tried in node.js, it did work well, here is  the code in nodejs: 
```javascript
const http = require("http");

var options = {
  path: "http://www.google.com",
  host: "the.proxy.com",
  port: 8080,
  headers: {
    Host: "www.google.com"
  }
};
http.get(options, function(res) {
  //console.log(res);
  res.pipe(process.stdout);
});
```

but the 'options' doesn't work in fibjs:
```javascript
const http = require("http");

var options = {
  path: "http://www.google.com",
  host: "the.proxy.com",
  port: 8080,
  headers: {
    Host: "www.google.com"
  }
};
let response = http.get("http://www.google.com", options);
console.log(response.body);
```

How do I tell fibjs' http.request to use the proxy?

**Comment by xicilion** [comment]
with this commit 9988668843f43992d8b01ea02644428691a9d870, you can use it like this:
```
const http = require("http");

http.proxyAgent = "http://the.proxy.com:8080";
let response = http.get("http://www.google.com", options);
console.log(response.body);
```

**Comment by jim4node** [comment]
@xicilion Thanks alot, look forward to seeing the new release as soon as possible!
