### ISSUE TITLE
http请求的client证书隔离

### ISSUE THREAD

**Issue by lhkzh** [fibjs/fibjs#541]
需求：微信支付多租户业务，微信针对每个商户发不同证书。现有ssl.load方式不合适。

**Comment by xicilion** [comment]
可以这样实现：
1，ssl.connect 支持 key 和 cert
2，HttpClient 支持 setClientCert
3，request 时，如果 HttpClient 包含 key 和 cert，则使用局部证书，否则使用缺省证书

**Comment by xicilion** [comment]
已经实现。
