### ISSUE TITLE
HttpServer/HttpsServer处理静态文件的问题

### ISSUE THREAD

**Issue by gmxyb** [fibjs/fibjs#546]
HttpServer/HttpsServer处理静态文件，文件名不能精确匹配而造成错误响应。

比如：后端实际存在 /abc.txt 文件。
当前端发起请求路径为  /abc.txt 时可以正确处理；
但是，前端发起请求路径为  /abc.txt. 或 /abc.txt.. 时，同样能请求到 /abc.txt，而不是返回 404

**Comment by xicilion** [comment]
这是 windows 操作系统的正常路径逻辑。
