### ISSUE TITLE
fibjs_gui.exe 不正常工作

### ISSUE THREAD

**Issue by richardo2016** [fibjs/fibjs#558]
平台: Windows x64
版本: >= 0.29.0
表现: fibjs_gui.exe 版本无法正常输出内容到控制台，console.log 无效，但能调用 gui 开启 webview 窗口

**重现**
- 直接运行 fibjs_gui.exe，无法打开窗口
- 在 terminal 中使用 fibjs_gui.exe 运行 console.log，发现既不打开窗口，也无输出

**Comment by xicilion** [comment]
已修复
