### ISSUE TITLE
Bug: `setInterval`/`clearInterval` hold test in win32(x86)

### ISSUE THREAD

**Issue by richardo2016** [fibjs/fibjs#578]
Platform: Windows
Arch: x86
Version: 0.31.0-dev

According to [This build](https://ci.appveyor.com/project/fibjs/fibjs/builds/33766755/job/i2crlqqdfulfe75t), `setInterval`/`clearInterval` would hold the process and never quit.

**Comment by xicilion** [comment]
Is it still happening now?

**Comment by richardo2016** [comment]
> Is it still happening now?

I haven't viewed on Windows CI of recent versions, maybe we could close this issue temporarily
