### ISSUE TITLE
smtp增强

### ISSUE THREAD

**Issue by lhkzh** [fibjs/fibjs#600]
目前连接不上微软的smtp地址。在ssl那一步就抛弃掉了
ssl://smtp.office365.com:587

利用curl对比，应该是fibjs对ssl连接上的处理细节问题
curl smtp://smtp.office365.com:587 -v --mail-from "your@outlook.com" --mail-rcpt "toyourtest@qq.com" --ssl -u "your@outlook.com:youroutlookpwd" -k --anyauth

**Comment by xicilion** [comment]
因为它不是 ssl，是 tcp，然后升级为 ssl，用 tcp 连接就可以了。

**Comment by lhkzh** [comment]
> 
> 
> 因为它不是 ssl，是 tcp，用 tcp 连接就可以了。
> <img alt="Screen Shot 2020-09-04 at 11 27 27 AM" width="636" src="https://user-images.githubusercontent.com/26833060/92196364-b4483d80-eea1-11ea-94fb-f8c9586a7762.png">

我去啊。。。这用这个端口居然tcp。
