### ISSUE TITLE
fibjs 0.31.0 HttpClient对象sslVerification属性 不生效

### ISSUE THREAD

**Issue by userding** [fibjs/fibjs#609]
设置sslVerification 为VERIFY_OPTIONAL 后 验证不通过的证书依然被中断

**Comment by xicilion** [comment]
代码是什么样的？

**Comment by userding** [comment]
> 代码是什么样的？

`const http = require('http')
const ssl = require('ssl')
ssl.loadRootCerts()

const hc = new http.Client()
hc.sslVerification = ssl.VERIFY_OPTIONAL
let res = hc.post('https://www.easy-mock.com/mock/5f508c9ea758c95f67d6eb86/learning/intergral')
console.log(res.statusCode);
`

**Comment by richardo2016** [comment]
> > 代码是什么样的？
> 
> `const http = require('http')
> const ssl = require('ssl')
> ssl.loadRootCerts()
> 
> const hc = new http.Client()
> hc.sslVerification = ssl.VERIFY_OPTIONAL
> let res = hc.post('https://www.easy-mock.com/mock/5f508c9ea758c95f67d6eb86/learning/intergral')
> console.log(res.statusCode);
> `

网站本身的证书好像有些问题，可以考虑开放 http 模式？

![image](https://user-images.githubusercontent.com/6339390/98246095-c717e500-1fac-11eb-8e49-69605e0c9f8b.png)
