### ISSUE TITLE
HttpRepeater未转发queryString

### ISSUE THREAD

**Issue by lhkzh** [fibjs/fibjs#611]
http.Repeater未转发queryString。

test code

<pre>
const http = require('http');
const svr = new http.Server(8885, {
    "/repeaterQueryString": req => new http.Repeater(`http://127.0.0.1:${svr.socket.localPort}/dump`).invoke(req),
    "/dump/repeaterQueryString": req => req.response.write(`queryString:${req.queryString}`)
});
svr.start();
const test = require('test');
test.setup();
describe('queryString', () => {
    it('not send ok', () => {
        var a = http.get("http://127.0.0.1:" + svr.socket.localPort + "/dump/repeaterQueryString", {query: {a: "aaa"}}).data.toString();
        var b = http.get("http://127.0.0.1:" + svr.socket.localPort + "/repeaterQueryString", {query: {a: "aaa"}}).data.toString();
        assert.equal(a, b);
    });
});
test.run();
</pre>

**Comment by xicilion** [comment]
已修复
