### ISSUE TITLE
http响应头Connection，返回多个

### ISSUE THREAD

**Issue by lhkzh** [fibjs/fibjs#617]
const http = require('http');
var svr = new http.Server(8086, (req) => {
    req.response.headers.clear();
    req.response.headers.set("Connection","close");
    req.response.write('hello, world');
});
svr.start();

curl -I localhost:8086   

HTTP/1.1 200 OK
Connection: close
Cache-Control: no-cache, no-store
Expires: -1
Connection: close
Content-Length: 12

浏览器会返回俩
Connection: close
Connection: keep-alive

**Comment by xicilion** [comment]
<img width="351" alt="Screen Shot 2020-11-24 at 5 21 27 PM" src="https://user-images.githubusercontent.com/26833060/100074263-7f80cc80-2e79-11eb-87dd-dd78f0ff2350.png">
用这个属性来修改

**Comment by lhkzh** [comment]
get！ 可行。
