### ISSUE TITLE
怎么对HttpClient的proxyAgent添加认证头

### ISSUE THREAD

**Issue by lhkzh** [fibjs/fibjs#618]
利用 proxyAgent属性，设置代理之后，有些代理需要认证。这时能否提供个方法或者属性，添加
Proxy-Authorization
这个代理上的消息头。

**Comment by richardo2016** [comment]
在请求的时候设置 headers

![image](https://user-images.githubusercontent.com/6339390/100072504-4a737a80-2e77-11eb-88ac-d5095ab1aa27.png)

**Comment by lhkzh** [comment]
这个方法可行。就是麻烦了点。
