### ISSUE TITLE
HttpClient don't react correctly to server's FIN in net pack.

### ISSUE THREAD

**Issue by richardo2016** [fibjs/fibjs#619]
![image](https://user-images.githubusercontent.com/6339390/100072709-932b3380-2e77-11eb-9f66-c2f6b703cb13.png)

![image](https://user-images.githubusercontent.com/6339390/100072734-9a524180-2e77-11eb-8464-76dd1d3d973a.png)

**Comment by xicilion** [comment]
有一些想法，可以采用乐观策略，对第一个 send 包结果进行判断，如果是对方已经关闭，则返回特殊错误，由 HttpClient 识别连接已关闭，进行重连处理。避免额外的长期连接检测和重复检测。
