### ISSUE TITLE
gui 模块可以支持webview2吗？

### ISSUE THREAD

**Issue by dongnanyanhai** [fibjs/fibjs#639]
微软新出的组件：
https://docs.microsoft.com/en-us/microsoft-edge/webview2/

谢谢！

**Comment by xicilion** [comment]
下一版支持了 cef，你可以尝试一下。webview2 接口还很不成熟，很多特性都没支持，或者支持的不完整。

**Comment by dongnanyanhai** [comment]
非常期待！

**Comment by xicilion** [comment]
0.32 release 了

**Comment by dongnanyanhai** [comment]
刷了几天文档居然没注意到增加一篇了，不好意思：
https://fibjs.org/docs/guide/desktop.md.html

功能非常强大，真赞啊！
