### ISSUE TITLE
Windows 下编译项目真的是劝退啊……

### ISSUE THREAD

**Issue by dongnanyanhai** [fibjs/fibjs#641]
首先遇到的问题是，fibjs\vender\build 文件里：

```
if [ "$HOST_OS" = "Windows" ]; then
	CMAKE_C_COMPILER=clang.exe
	CMAKE_CXX_COMPILER=clang++.exe
```

要改成
```
if [ "$HOST_OS" = "Windows" ]; then
	CMAKE_C_COMPILER=clang-cl.exe
	CMAKE_CXX_COMPILER=clang-cpp.exe
```

然后，就卡在下面错误：

>     clang-cl: error: no such file or directory: 'C:/Program Files/Git/nologo'
>     clang-cl: error: no such file or directory: 'C:/Program Files/Git/DWIN32'
>     clang-cl: error: no such file or directory: 'C:/Program Files/Git/D_WINDOWS'
>     clang-cl: error: no such file or directory: 'C:/Program Files/Git/W3'
>     clang-cl: error: no such file or directory: 'C:/Program Files/Git/MDd'
>     clang-cl: error: no such file or directory: 'C:/Program Files/Git/Zi'
>     clang-cl: error: no such file or directory: 'C:/Program Files/Git/Ob0'
>     clang-cl: error: no such file or directory: 'C:/Program Files/Git/Od'
>     clang-cl: error: no such file or directory: 'C:/Program Files/Git/RTC1'

目前在[clang doc](https://clang.llvm.org/docs/UsersManual.html#clang-cl) 找到说明：

> Options that are not known to clang-cl will be ignored by default. Use the -Werror=unknown-argument option in order to treat them as errors. If these options are spelled with a leading /, they will be mistaken for a filename:
> clang-cl.exe: error: no such file or directory: '/foobar'

知道是参数里的/产生的问题，但搜了一圈没找到响应参数，实在不知道该如何解决……

**Comment by xicilion** [comment]
拉 dev 版本编译吧，release 的 windows 编译的确就是劝退，我过年前后在这个事情上搞了半个多月。后来忍无可忍，全部重写了。

**Comment by dongnanyanhai** [comment]
好好好，非常感谢，我找资料都找到头晕了！

**Comment by dongnanyanhai** [comment]
编译成功了，dev版本一个命令搞定，真幸福！
