### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by carlocab** [fibjs/fibjs#642]
Hi there,

The `GPL-3.0` license identifier is deprecated, and has been replaced with `GPL-3.0-only` and `GPL-3.0-or-later`. (See, for instance, https://spdx.org/licenses/.)

Could you clarify which identifier applies to your software, please? Thank you!

Related: #291, https://github.com/Homebrew/homebrew-core/pull/73588

**Comment by richardo2016** [comment]
@carlocab Hi, we could clarify it soon. After we determine which identifier to be applied, should I leave comment here or in that issue #291 ? Or should I replace our License in repository?

**Comment by carlocab** [comment]
Leaving a comment here would be great, but you should probably also replace the `LICENSE` file in this repo.

**Comment by richardo2016** [comment]
> Leaving a comment here would be great, but you should probably also replace the `LICENSE` file in this repo. Thanks again.

Thanks for your contacting. Finally we decided to use `GPL-3.0-only`, we will update LICENSE file on next release.

**Comment by carlocab** [comment]
Thank you for the clarification!
