### ISSUE TITLE
服务端模块热更新方案的内存问题

### ISSUE THREAD

**Issue by dongnanyanhai** [fibjs/fibjs#644]
按[文档](https://fibjs.org/docs/guide/server-hot-update.md.html)中的说明去实现模块热更新，发现内存占用会不断增加；

尝试使用SandBox.freeze()去冻结，会得到Error: [-100009] Invalid procedure call.的错误。

想通过fs.watch来监听文件变化，再更新模块，发现当监听的是目录时，目录下任意文件修改都会触发事件，但无法知道被修改的具体文件名称。

**Comment by xicilion** [comment]
你看到内存增加是因为还没有触发 v8 的 gc，当 v8 开始 gc 的时候，内存就会被释放。
你也可以在热升级后主动调用 `GC();` 来释放内存。

为了避免 watch 太频繁更新模块，你可以只让它刷新一个标记，然后自己在一个定时器里自己决定是不是启动热更新。

**Comment by dongnanyanhai** [comment]
好的，谢谢！

**Comment by lhkzh** [comment]
@dongnanyanhai   我们是监听进程新号/监控文件夹变化 做热更新的。
