### ISSUE TITLE
Bug: `bson.decode`results in an abnormal exit of fibjs

### ISSUE THREAD

**Issue by zyscoder** [fibjs/fibjs#648]
# Bug Report
* **Version**: v0.32.1
* **Platform**:  Linux 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: bson.decode

### What steps will reproduce the bug?
Setup a fibjs instance,
```
» fibjs
```
and run the following javascript code.
```
require('bson').decode('zyscoder')
```
Then the fibjs instance exits abnormally.

### How often does it reproduce? Is there a required condition?
This problem can always be triggered following the steps above.

### What is the expected behavior?
If any error occurs, an exception or other similar error-reporting stuff should be thrown just like node.js. There is no reason to crash the whole fibjs process.

### What do you see instead?
```
» fibjs
Welcome to fibjs 0.32.1.
Type ".help" for more information.
> require('bson').decode('zyscoder')
unknown type: 111
error: unknown type: 111                                                                                                                                                                                                  
```

**Comment by zyscoder** [comment]
Hi guys, nice to meet you.
I noticed this project FibJS by accident and am very happy to see you a group of Chinese to set up this project (I am Chinese too). I write in English for convenience for more contributors to join in. In my understanding, can I treat fibJS as an alternative solution (maybe a faster and user-friendly one?) for node.js? 
I am not a JavaScript developer. I'm doing research to detect bugs and vulnerabilities in JavaScript runtime and have found several bugs in node.js. Maybe some of my issues do not make sense, and thanks for your patient reply in advance.

**Comment by zyscoder** [comment]
For this issue, if any error occurs, throwing an exception as a hint for developers may be a better way rather than crash the fibjs instance, just like the way node.js handles errors and exceptions. If any wrong with my understanding of this project, wish you can remind me so that I can adjust my testing.

**Comment by xicilion** [comment]
It's great, thank you for your work, I will check what the problem is as soon as possible.

**Comment by zyscoder** [comment]
Would you mind giving me a tag of "Bug" for my issues which you confirmed? It's important for my publication of my work. Thank you very much!
