### ISSUE TITLE
Bug: `crypto.simpleRandomBytes` results in a segmentation fault

### ISSUE THREAD

**Issue by zyscoder** [fibjs/fibjs#657]
# Bug Report
* **Version**: v0.32.1
* **Platform**:  Linux 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: crypto.simpleRandomBytes

### What steps will reproduce the bug?
Setup a fibjs instance,
```
» fibjs
```
and run the following javascript code.
```
crypto = require('crypto');crypto.simpleRandomBytes(2147483647);
```
Then the fibjs instance occurs a segmentation fault.

### How often does it reproduce? Is there a required condition?
This problem can always be triggered following the steps above.

### What is the expected behavior?
If any error occurs, an exception or other similar error-reporting stuff should be thrown just like node.js. There is no reason to crash the whole fibjs process.

### What do you see instead?
```
» fibjs
Welcome to fibjs 0.32.1.
Type ".help" for more information.
> crypto = require('crypto');crypto.simpleRandomBytes(2147483647);
[2]    113734 segmentation fault (core dumped)  fibjs
                                                                                                                                                                             
```

**Comment by xicilion** [comment]
The reason for this error is that the console.log output is too long.
