### ISSUE TITLE
Bug: `base32.encode` results in an illegal hardware instruction error

### ISSUE THREAD

**Issue by zyscoder** [fibjs/fibjs#658]
# Bug Report
* **Version**: v0.33.0-dev
* **Platform**:  Linux 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: base32.encode

### What steps will reproduce the bug?
Setup a fibjs instance,
```
» fibjs
```
and run the following javascript code.
```
base32 = require('base32');base32.encode(530543385);
```
Then the fibjs instance occurs a crash.

### How often does it reproduce? Is there a required condition?
This problem can always be triggered following the steps above.

### What is the expected behavior?
If any error occurs, an exception or other similar error-reporting stuff should be thrown. There is no reason to crash the whole fibjs process.

### What do you see instead?
```
» fibjs
Welcome to fibjs 0.33.0-dev.
Type ".help" for more information.
> base32 = require('base32');base32.encode(530543385);

<--- Last few GCs --->

[122922:0x7f78b80dfac0]    15549 ms: Mark-sweep 1400.9 (1420.6) -> 1400.9 (1422.1) MB, 36.2 / 0.0 ms  (average mu = 0.234, current mu = 0.183) allocation failure scavenge might not succeed
[122922:0x7f78b80dfac0]    15584 ms: Mark-sweep 1402.1 (1422.1) -> 1402.0 (1423.1) MB, 31.9 / 0.0 ms  (average mu = 0.173, current mu = 0.102) allocation failure scavenge might not succeed


<--- JS stacktrace --->


#
# Fatal javascript OOM in Ineffective mark-compacts near heap limit
#

[1]    122922 illegal hardware instruction (core dumped)  /home/zys/Toolchains/fibjs/bin/Linux_amd64_release/fibjs
                                                                                                                                                                             
```

**Comment by xicilion** [comment]
The reason for this error is that the console.log output is too long. And the following is the same problem.
#657

**Comment by xicilion** [comment]
I probably know the cause of this problem, and I need to verify it.
