### ISSUE TITLE
Bug: `bson.decode` results in an abort

### ISSUE THREAD

**Issue by zyscoder** [fibjs/fibjs#668]
# Bug Report
* **Version**: v0.33.0-dev
* **Platform**:  Linux 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: bson.decode

### What steps will reproduce the bug?
Setup a fibjs instance,
```
» fibjs
```
and run the following javascript code.
```
bson = require('bson');decodeBuf = bson.decode(undefined);
encodeBuf = bson.encode(decodeBuf);
encodeReverse = encodeBuf.reverse();
bson.decode(encodeReverse);
```
Then the fibjs instance occurs an abort.

### How often does it reproduce? Is there a required condition?
This problem can always be triggered following the steps above.

### What is the expected behavior?
If any error occurs, an exception or other similar error-reporting stuff should be thrown. There is no reason to crash the whole fibjs process. 
### What do you see instead?
```
» fibjs
Welcome to fibjs 0.33.0-dev.
Type ".help" for more information.
> bson = require('bson');decodeBuf = bson.decode(undefined);
{}
> encodeBuf = bson.encode(decodeBuf);
<Buffer 05 00 00 00 00>
> encodeReverse = encodeBuf.reverse();
<Buffer 00 00 00 00 05>
> bson.decode(encodeReverse);
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    101722 abort (core dumped)  /home/zys/Toolchains/fibjs/bin/Linux_amd64_release/fibjs
```

**Comment by xicilion** [comment]
This is an internal module that needs to be discarded, not exposed, and has been processed.
