### ISSUE TITLE
Much more OOM and illegal hardware instruction occurs in fibjs compared with nodejs

### ISSUE THREAD

**Issue by zyscoder** [fibjs/fibjs#676]
* **Version**: v0.33.0-dev
* **Platform**:  Linux 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: Memory manager

During my testing for nodejs and fibjs, it seems that the memory manager of fibjs is much weaker compared with the one of nodejs. Much more OOM occurs in fibjs and results in illegal hardware instruction.

### What steps will reproduce the bug?
Setup a fibjs instance,
```
» fibjs
```
and run the following javascript code.
```
buf = global.Buffer.alloc(1498850885);
buf.values();
```
Then the fibjs instance occurs an OOM and illegal hardware instruction.
Noticed that the same testing code would not abort a nodejs instance (my version of nodejs is v16.0.0-pre).

### How often does it reproduce? Is there a required condition?
This problem can always be triggered following the steps above.

### What is the expected behavior?
Work as robustly as nodejs.
### What do you see instead?
```
» fibjs
Welcome to fibjs 0.33.0-dev.
Type ".help" for more information.
> buf = global.Buffer.alloc(1498850885);

<Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 1498850835 more bytes>
> buf.values();

<--- Last few GCs --->
[42333:0x7f9f44c08740]      642 ms: Mark-sweep 2.0 (4.1) -> 1.7 (4.1) MB, 3.6 / 0.1 ms  (average mu = 1.000, current mu = 1.000) external memory pressure GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xcb7f35d40fd]
Security context: 0x2cf07a81a171 <JSObject>
    1: /* anonymous */ [0x2cf07a87f7c1] [repl:1] [bytecode=0x2cf07a87f761 offset=11](this=0x04b764702201 <JSGlobal Object>)
    2: InternalFrame [pc: 0xcb7f358b6c9]
    3: EntryFrame [pc: 0xcb7f35862fe]

==== Details ================================================

[0]: ExitFrame [pc: 0xcb7f35d40fd]
[1]: /* anonymous */ [0x2cf07a87f7c1] [repl:1] [bytecode=0x...


#
# Fatal javascript OOM in invalid array length
#

[1]    42333 illegal hardware instruction (core dumped)  /home/zys/Toolchains/fibjs/bin/Linux_amd64_release/fibjs
```

**Comment by xicilion** [comment]
Well, this is a set of the same problems, let me study how to solve them. thank.
