### ISSUE TITLE
Bug: `crypto.randomArt` results in a segmentation fault

### ISSUE THREAD

**Issue by zyscoder** [fibjs/fibjs#677]
# Bug Report
* **Version**: v0.33.0-dev
* **Platform**:  Linux 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: crypto.randomArt

### What steps will reproduce the bug?
Setup a fibjs instance,
```
» fibjs
```
and run the following javascript code.
```
crypto = require('crypto'); crypto.randomArt(undefined, '', 1064203628);
```
Then the fibjs instance occurs a segmentation fault.

### How often does it reproduce? Is there a required condition?
This problem can always be triggered following the steps above.

### What is the expected behavior?
If any error occurs, an exception or other similar error-reporting stuff should be thrown. There is no reason to crash the whole fibjs process. 
### What do you see instead?
```
» fibjs
Welcome to fibjs 0.33.0-dev.
Type ".help" for more information.
> crypto = require('crypto'); crypto.randomArt(undefined, '', 1064203628);
[1]    99005 segmentation fault (core dumped)  /home/zys/Toolchains/fibjs/bin/Linux_amd64_release/fibjs
```

**Comment by zyscoder** [comment]
It seems to be different from #662, which would not crash the latest version of fibjs now.

**Comment by xicilion** [comment]
Yes, the reason for this problem is that the required matrix size is too large.
