### ISSUE TITLE
Bug: `hex.encode` results in an OOM

### ISSUE THREAD

**Issue by zyscoder** [fibjs/fibjs#678]
# Bug Report
* **Version**: v0.33.0-dev
* **Platform**:  Linux 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: hex.encode

### What steps will reproduce the bug?
Setup a fibjs instance,
```
» fibjs
```
and run the following javascript code.
```
hex = require('hex');hex.encode(502045304);
```
Then the fibjs instance occurs an OOM and crashes.

### How often does it reproduce? Is there a required condition?
This problem can always be triggered following the steps above.

### What is the expected behavior?
As said in [fibjs' docs](https://fibjs.org/docs/manual/module/ifs/hex.md.html), `hex.encode` only receive `Buffer` type as the parameter. Is there a missing typing check for the parameter of `hex.encode`?
If any error occurs, an exception or other similar error-reporting stuff should be thrown. There is no reason to crash the whole fibjs process. 
### What do you see instead?
```
» fibjs
Welcome to fibjs 0.33.0-dev.
Type ".help" for more information.
> hex = require('hex');hex.encode(502045304);                                              

<--- Last few GCs --->

[71372:0x7f917927fe80]    32382 ms: Mark-sweep 1919.6 (1951.2) -> 1919.6 (1951.2) MB, 29.8 / 0.0 ms  (average mu = 0.949, current mu = 0.001) last resort GC in old space requested
[71372:0x7f917927fe80]    32413 ms: Mark-sweep 1919.6 (1951.2) -> 1919.6 (1951.2) MB, 30.8 / 0.0 ms  (average mu = 0.900, current mu = 0.001) last resort GC in old space requested


<--- JS stacktrace --->


#
# Fatal javascript OOM in CALL_AND_RETRY_LAST
#

[1]    71372 illegal hardware instruction (core dumped)  /home/zys/Toolchains/fibjs/bin/Linux_amd64_release/fibjs
```

**Comment by xicilion** [comment]
In fibjs, when the parameter requires an object, and this object allows a single parameter to be constructed, fibjs will automatically complete the data type conversion, so when you pass num in the parameter that requires Buffer type, you actually pass `new Buffer(num)`.

**Comment by xicilion** [comment]
This is a completely internal memory management problem in v8.  `new Buffer(num)` is successful, `hex.encode()` is also normal, and the result is successfully returned to v8, but when the string is retrieved from v8 again, because the string is too large and exceeds memory limit, this error occurs.

**Comment by xicilion** [comment]
After several days of research and development, I finally implemented zero-copy transmission of strings between fibjs and v8, which greatly improved the performance of large strings and improved the memory management of v8.

Thank you very much, your work has brought great help to this project.
