### ISSUE TITLE
http.Cookie 的expires解析有问题

### ISSUE THREAD

**Issue by lhkzh** [fibjs/fibjs#681]
使用其他服务器语言（例如php），返回的cookie有效期时，fibjs的cookie.expire 解析失败。

可以使用下面示例跑一下-.- 
`const http = require('http');
var svr = new http.Server(8080, (req) => {
    req.response.addHeader({"Set-Cookie":"tb=abcd; expires=Sun, 17-Jan-2038 19:14:07 GMT; path=/;"});
    req.response.write('hello, world');
});
svr.start();`

客户端
`var r=http.get("http://localhost:8080");console.log(r.cookies[0].expires)`

直接js解析是没问题的
`console.log( new Date(Date.parse(Sun, 17-Jan-2038 19:14:07 GMT)) )`

**Comment by lhkzh** [comment]
也可以顺手，给 http.Cookie 添加个 SameSite 属性。哈哈

**Comment by xicilion** [comment]
http 的 Date 格式是有特殊要求的，和 js 的格式不完全兼容，参见：https://tools.ietf.org/html/rfc7231#section-7.1.1.2
建议使用 response.addCookie 来添加 cookie，https://fibjs.org/docs/manual/object/ifs/httpresponse.md.html#addCookie

**Comment by xicilion** [comment]
SameSite 特性需要改一些逻辑，先增加个 issue 挂着。
