### ISSUE TITLE
cipher.getAuthTag支持

### ISSUE THREAD

**Issue by lhkzh** [fibjs/fibjs#686]
应用场景（官方游戏防沉迷接口加密 AES-128-GCM ）
https://blog.csdn.net/yushiershi/article/details/105064835
前使用fibjs实现上，遇到 cipher.getAuthTag(); 这个方法木有，对照搞不下去了。
cipher.setAuthTag 解码用

这里mark防止忘记（群里提过）

**Comment by xicilion** [comment]
https://github.com/fibjs/fibjs/commit/41c9f9e86b045e68f0dcd67393e274506e3fe66d
