### ISSUE TITLE
uuid.random在windows性能感觉有问题

### ISSUE THREAD

**Issue by lhkzh** [fibjs/fibjs#698]
snowflake几毫秒
console.time("snow");for(var i=0;i<1000;i++){ uuid.snowflake().toString("hex") };console.timeEnd("snow")；
random需要3.x秒，理论上只随机应该不要这么久  
console.time("random");for(var i=0;i<1000;i++){ uuid.random().toString("hex") };console.timeEnd("random") 

v0.33 , win64,  Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
笔记本电脑，居然要3.x秒。这个太费时间了吧 -.-

**Comment by gmxyb** [comment]
uuid.random()确实很慢，大约 600个/秒。
建议用 crypto.simpleRandomBytes(16) 代替，能达到  40万 个/秒

**Comment by xicilion** [comment]
uuid.random 的实现使用的是系统硬件随机数，因此会慢一些。
