### ISSUE TITLE
v0.33 fs module test case failed

### ISSUE THREAD

**Issue by hellllll0world** [fibjs/fibjs#706]
![1e6deb5a3ce3f18fb52bbee0c610663](https://user-images.githubusercontent.com/12581637/123925615-aaa63e00-d9bd-11eb-9572-90821c35d26d.jpg)

**Comment by richardo2016** [comment]
请提供下复现对应的复现环境

- 系统:
- 架构:
- fibjs 版本:

**Comment by xicilion** [comment]
This error depends on the operating system environment where the test is run, so it is not a fibjs error.
