### ISSUE TITLE
http请求解析问题

### ISSUE THREAD

**Issue by lhkzh** [fibjs/fibjs#718]
这么写请求时，服务器解析的address不正确
//url本来带了参数，又 带query的时候。

`http.get("http://127.0.0.1:8048/?aa=111",{query:{bb:"233"}}).statusCode

new (require("http").Server)(8048, (req) => {  console.log(req.address,req.query.toJSON()); req.response.write('ok');  }).start();`

**Comment by Hi-Rube** [comment]
谢谢哦！ 啦啦啦啦啦啦啦！ 啊哈哈哈哈哈！

**Comment by asionius** [comment]
您好，我已收到您的邮件~上线后我会尽快阅读~。

**Comment by xicilion** [comment]
问题是 `http://127.0.0.1:8048/?aa=111?bb=233` 的解析方式。我测试了一下，node 返回了同样的 `{ aa: '111?bb=233' }` 结果。此时，?aa= 部分也会被解析为 query 。

**Comment by lhkzh** [comment]
大概是我标题说错了，应该是 client 拼装部分的问题0.0”。 和解析没关系，解析正确的。

> 问题是 `http://127.0.0.1:8048/?aa=111?bb=233` 的解析方式。我测试了一下，node 返回了同样的 `{ aa: '111?bb=233' }` 结果。此时，?aa= 部分也会被解析为 query 。

**Comment by xicilion** [comment]
在最近一次 HttpClient 重构中解决了这个问题：
https://github.com/fibjs/fibjs/commit/ea8e92c39ce1b7c00a227c3e35a1ea0649896c30
