### ISSUE TITLE
此提交不属于此存储库上的任何分支，并且可能属于存储库外部的分支。

### ISSUE THREAD

**Issue by marklove5102** [fibjs/fibjs#725]
https://github.com/fibjs/fibjs/blob/4ea2e201ccffe355d373fd0ea02edff8a980f165/test/coroutine_test.js
这是啥情况  找了半天也没找到 4ea2e201ccffe355d373fd0ea02edff8a980f165
但是这个页面有
https://github.com/fibjs/fibjs/commits/4ea2e201ccffe355d373fd0ea02edff8a980f165
。。。。。。。
幽灵了？隐身分支？

**Comment by xicilion** [comment]
可能是某个没合并的 pr 吧
