### ISSUE TITLE
http://fibjs.org/ 502

### ISSUE THREAD

**Issue by suconghou** [fibjs/fibjs#731]
官网都502好久了, 文档都看不了了

另外, 能否发个新的release work on alpine

**Comment by xuyu199742** [comment]
估计早不维护了

**Comment by Hi-Rube** [comment]
谢谢哦！ 啦啦啦啦啦啦啦！ 啊哈哈哈哈哈！

**Comment by asionius** [comment]
您好，我已收到您的邮件~上线后我会尽快阅读~。

**Comment by xicilion** [comment]
域名服务被服务商误封了，请访问 https://fibjs.net
我们在努力与服务商申诉。

**Comment by xicilion** [comment]
fibjs.org 域名经过仲裁已经恢复了。
