### ISSUE TITLE
Class static initialization blocks SyntaxError

### ISSUE THREAD

**Issue by forchid** [fibjs/fibjs#732]
Issue: The ES6 feature "Class static initialization blocks" not supported in the current fibjs, but it's supported in node.
Version: fibjs v0.35.0, node v16.13.0.

# Test case in fibjs
```js
> class Test {
 ... static {}
repl:2:8
static {}
       ^
SyntaxError: Unexpected token '{'
>
```
# Test case in node
```js
> class Test {
... static {}
... }
undefined
>
```

**Comment by Hi-Rube** [comment]
谢谢哦！ 啦啦啦啦啦啦啦！ 啊哈哈哈哈哈！

**Comment by xicilion** [comment]
This is caused by an earlier v8 version, and the next v8 upgrade will fix it.

**Comment by forchid** [comment]
@xicilion Thanks!

**Comment by xicilion** [comment]
it's done. https://github.com/fibjs/fibjs/commit/987aa5b1005c5c5b409cd2d624970f102f8c5bf4
