### ISSUE TITLE
'Error: [4092] permission denied' raised after calling socket bind pipe on windows

### ISSUE THREAD

**Issue by forchid** [fibjs/fibjs#740]
Windows 10.
# Test case
```js
let server = new net.Socket(net.AF_PIPE);
server.bind('pipe://./pipe/proc1');
server.listen();
```

**Comment by lhkzh** [comment]
try like this
var path = "//.//pipe/proc1"; // 'pipe://./pipe/proc1'
let server = new net.Socket(net.AF_PIPE);
server.bind(path );
server.listen();

**Comment by forchid** [comment]
> "//./pipe/proc1"

It works. It's not correct in (fibjs website)[https://fibjs.org/docs/manual/module/ifs/net.md.html#connect]. @lhkzh Thank you!

**Comment by forchid** [comment]
Oh, it's my problem! The "static Stream net.connect(String url, Integer timeout = 0)" needs 'pipe:' prefix(eg. 'pipe://./pipe/proc1'), but the Sockect.connect() doesn't this prefix(eg. '//./pipe/proc1')!
