### ISSUE TITLE
Add LoongArch new-world CI

### ISSUE THREAD

**Issue by xen0n** [fibjs/fibjs#770]
As @xry111 noted in https://github.com/loongson-community/areweloongyet/issues/127, [The existing loong64 CI](https://github.com/fibjs/fibjs/blob/865eafa9018fa99d4eff0047f96bb826c858bafc/dockerfiles/linux-build-env.loong64) is targetting Loongnix, which is "old-world", and *not* compatible with systems built entirely from upstream sources.

We need to distinguish between the two ABIs by renaming the existing loong64 target, then adding a cross image built from upstream sources ([crosstool-ng](https://github.com/crosstool-ng/crosstool-ng) is known to work).

As for naming: it's customary for the *new world ABI* to be named `loong64` when it comes to Docker (architecture names there follow the Go `GOARCH` convention), but there isn't a widely accepted name for the old world ABI. Loongson themselves may prefer calling the old world as `abi1` or `abi1.0`, but in the wild a shorter name like `loong64ow` could be acceptable too.

Related reading material: https://areweloongyet.com/docs/old-and-new-worlds

**Comment by xicilion** [comment]
Resolved some compatibility issues regarding loongarch new worlds, changed loong64 for building new world releases, added loong64ow for old world releases.

https://github.com/fibjs/fibjs/commit/c4f5ac1dfd63bdc09cc952c3b70a91beb2e5293d
