### ISSUE TITLE
missing `fullsrc.zip` for `0.37.0` release

### ISSUE THREAD

**Issue by chenrui333** [fibjs/fibjs#771]
👋 it looks like `fullsrc.zip` is missing for `0.37.0` release, raise this issue for some awareness! Thanks!

**Comment by xicilion** [comment]
The fullsrc.zip attachment has been added manually, I lost the code that automatically generates fullsrc.zip when I refactored the ci script.

**Comment by chenrui333** [comment]
Thanks @xicilion!

Close in favor of https://github.com/Homebrew/homebrew-core/pull/162994
