### ISSUE TITLE
为什么要移除gd模块呢

### ISSUE THREAD

**Issue by An-uking** [fibjs/fibjs#772]
为什么要移除gd模块呢，我感觉用起还不错，可以做图片裁剪还可以做验证码等

**Comment by xicilion** [comment]
fibjs has better compatibility with npm, allowing you to leverage the npm ecosystem of modules for more interesting features.
For example, for image processing, we suggest you try https://www.npmjs.com/package/canvaskit-wasm for better image processing support.
![39951705259918_ pic](https://github.com/fibjs/fibjs/assets/26833060/a15a9cc0-e5c0-4e99-9045-cf09c951ff9d)
