### ISSUE TITLE
当content-type不为application/x-www-form-urlencoded这个时，读取req.form报错

### ISSUE THREAD

**Issue by An-uking** [fibjs/fibjs#773]
当content-type不为application/x-www-form-urlencoded这个时，读取req.form报错
抛出异常代码在fibjs/src/http/HttpRequest.cpp文件449行

如果用户没有按规定的content-type使用接口，后台则会报错。期望能正常读取 不要抛出异常，目前解决是用try  catch包裹req.form

**Comment by forchid** [comment]
> 当content-type不为application/x-www-form-urlencoded这个时，读取req.form报错 抛出异常代码在fibjs/src/http/HttpRequest.cpp文件449行
> 
> 如果用户没有按规定的content-type使用接口，后台则会报错。期望能正常读取 不要抛出异常，目前解决是用try catch包裹req.form

如果你要灵活性，可以使用[req.data](https://fibjs.org/docs/manual/object/ifs/httprequest.md.html#data).
req.form就是用来处理form urlencoded编码格式数据的。如果你传个json过来格式不对啊，必须抛异常的。

**Comment by An-uking** [comment]
@forchid 如果传的时是非urlencoded编码格式数据,让form={}，我可以读取不到，但是不应该让它读取时报错

**Comment by forchid** [comment]
> @forchid 如果传的时是非urlencoded编码格式数据,让form={}，我可以读取不到，但是不应该让它读取时报错

这样的处理方式会把bug隐藏起来很难发现。
