### ISSUE TITLE
希望增加redis模块对执行lua脚本的支持

### ISSUE THREAD

**Issue by An-uking** [fibjs/fibjs#774]
希望增加redis模块对执行lua脚本的支持

**Comment by xicilion** [comment]
这是什么奇怪的需求？

**Comment by An-uking** [comment]
尝试写限流，对redis的数据要原子操作，并发的时候锁不住。在网上查到nodejs里的解决办法就是利用lua脚本获取redis的原子锁
redis.eval(luascript)。你们有没有好的限流代码可以参考一下

**Comment by forchid** [comment]
> 希望增加redis模块对执行lua脚本的支持

The [command()](https://fibjs.org/docs/manual/object/ifs/redis.md.html#command) function supports lua script in fibjs Redis object. eg.
```shell
>const db = require('db')
>var redis = db.open('redis://localhost')
>var res = redis.command("eval", "local msg = 'abc'; return msg;", 0)
>console.log(res.toString()) // print "abc"
```

**Comment by forchid** [comment]
> 尝试写限流，对redis的数据要原子操作，并发的时候锁不住。在网上查到nodejs里的解决办法就是利用lua脚本获取redis的原子锁 redis.eval(luascript)。你们有没有好的限流代码可以参考一下

```js
const db = require('db')
var redis = db.open('redis://localhost')
var result = redis.command("eval", "local msg1 = KEYS[1];local msg2 = KEYS[2];local msg3 = ARGV[1];local msg4 = ARGV[2];return msg1 .. msg2 .. msg3 .. msg4;",2, "a", "b", "c", "d") // 执行带有2个keys和args的lua script
console.log(result + "") // print "abcd"
redis.close()
```

**Comment by xicilion** [comment]
nodejs 方案正确的返回结果时什么？fibjs 的结果是什么？

**Comment by An-uking** [comment]
@forchid 谢谢
