### ISSUE TITLE
How to access or determine the main module

### ISSUE THREAD

**Issue by forchid** [fibjs/fibjs#780]
In my a fibjs application, there is a requirement for determining the current file is whether or not the main module, and I can't find a method to do this in fibjs.  But in nodejs, It can be done by [`require.main`](https://nodejs.org/download/docs/v16.20.2/api/modules.html#accessing-the-main-module).
# Versions
Fibjs v0.37.0, nodejs v20.10.0.
# Test cases
```js
// main.js
const mod = require('./mod.js');
console.log('main: main file - %s', require.main.filename);
mod.run();
```
```js
// mod.js
console.log('mod: main file - %s', require.main.filename);
module.exports = {
    run() {
        console.log('mod.run(): main file - %s', require.main.filename);
    }
};
```
# Test result
```shell
>fibjs main.js
...\mod.js:2:49
console.log('mod: main file - %s', require.main.filename);
                                                ^
TypeError: Cannot read properties of undefined (reading 'filename')
    at ...\mod.js:2:49
    at ...\main.js:2:13
```

```shell
>node main.js
mod: main file - ...\main.js
main: main file - ...\main.js
mod.run(): main file - ...\main.js
```

**Comment by xicilion** [comment]
You can detect whether it is the entry script by checking `require.main === module`. This is valid in both Node.js and fibjs.
