### ISSUE TITLE
Support for stripping type annotations

### ISSUE THREAD

**Issue by nezarati** [fibjs/fibjs#786]
As I know, FibJS has two solutions to run `.ts` files:
- `SandBox.setModuleCompiler`
- `fib-typify`

Node.js recently provided the `--experimental-strip-types` flag for initial TypeScript support. This flag is limited to inline type annotations and doesn't support features like `enums` or `namespaces`. It allows running TypeScript files without prior transformation by stripping type annotations.

Also, JavaScript engines are moving towards native support for type annotations, as seen in the [Type Annotations proposal](https://github.com/tc39/proposal-type-annotations).

Does FibJS have plans to implement a similar feature for stripping type annotations?

This feature is useful for users by:
- Reducing build times by eliminating unneeded transformation steps.
- Leveraging native engine support for type annotations as it becomes available.

**Comment by xicilion** [comment]
Thank you very much for your feedback. I am also keeping an eye on the support of TypeScript by node.js. It will be very exciting if we can directly run ts files. From what I know, node.js supports ts compilation by embedding the amaro wasm module, which is a great idea, although I have some concerns about the compilation speed of amaro. fibjs is planning to natively support loading ts modules.

**Comment by xicilion** [comment]
![mmexport1726725708622.jpg](https://github.com/user-attachments/assets/fb7f58fa-f2d9-4603-a460-b0c5c60fe295)

it is running.

**Comment by xicilion** [comment]
supported.
https://github.com/fibjs/fibjs/commit/da21f4c2ee30b125919860195638209d84b2d053
